version: "3.7"

# Define services
services:
  # App backend service
  backend:
    # Configuration for building the docker image for the backend service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/N11_CREDIT_APP
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - backend

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: N11_CREDIT_APP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

networks:
  backend:
